 repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=5000']
  - repo: local
    hooks:
      - id: detect-web3-private-key
        name: Detect Web3 Private Key
        entry: python scripts/detect_web3_private_keys.py
        language: python
        stages: [pre-commit]
        additional_dependencies: ['eth-account']
        exclude: 'poetry.lock'