site_name: Prediction Market Agent Tooling
nav:
  - Home: index.md
  - Prediction Markets: predictionmarkets.md
  - Quickstart
    - Dependencies: dependencies.md
    - Install and Configure: install.md
  - Contributing: contributing.md

theme:
  name: material