site_name: Prediction Market Agent Tooling
nav:
  - Home: index.md
  - Prediction Markets: predictionmarkets.md
  - Dependencies: dependencies.md
  - Quickstart: quistart.md
  - Contributing: contributing.md

theme:
  name: material

