site_name: Prediction Market Agent Tooling

nav:
  - Home: index.md
  - Prediction Market Agents:
      - Overview: predictionmarkets.md
      - Dependencies: dependencies.md
      - Quickstart: quickstart.md
  - Agent Development:
      - Deployable Trader Agent: deployabletraderagent.md
      - Benchmarker: benchmarker.md
      - Example Agent: exampleagent.md
      - Deploy with Safe: deploywithsafe.md
  - API Reference: api.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.expand

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_if_no_docstring: true
            separate_signature: true
            members_order: source
            docstring_section_style: table
            show_signature_annotations: true
            show_bases: true
            show_submodules: true
            merge_init_into_class: true
            show_if_no_docstring: true
            inherited_members: true
            members: true
            filters: ["!^_"]
            extra:
              show_inheritance: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
