site_name: Prediction Market Agent Tooling
nav:
  - Home: index.md
  - Prediction Markets: predictionmarkets.md
  - Dependencies: dependencies.md
  - Quickstart: quickstart.md
  - DeployableTraderAgent: deployabletraderagent.md
  - ExampleAgent: exampleagent.md
  - Contributing: contributing.md

theme:
  name: material

